laserscan_toolbox_node:
  ros__parameters:
    #common
    rate: 10.0 #hz
    topic_out: "scan" 
    new_frame: "base2_link"

    #debugging
    debug: true
    debug_file_path: "/home/jrluser/Desktop/call_m_workspace/lasertoolbox_debug.txt"
    show_ranges: false

    #output settings
    angle_min: 0.0 #0.0
    angle_max: 6.283185307
    angle_increment: 0.008726647 #0.017453293 for 360 values resolution = 1deg precision
    range_min: 0.0 #m
    range_max: 12.0 #m

    #advanced output settings
    auto_set: true #If true, the settings below will be set automatically using the first source
    time_increment: 0.0 #s
    scan_time: 0.0 #s

    #sources
    sources: cam1 cam2 #lidar1_simu lidar2_simu lidar1 lidar2 #cam1 cam2

    lidar1_simu:
      topic: "lidar1_simu/scan"
      start_angle: 0.785398163 #45 deg in source frame
      end_angle: 5.497787144 #-45 = 315 deg in source frame
      scan_angle_offset: 0.0 #180 deg with rpLidars, but simulation doens't need shift as the start and end angles are well specified in the lidar frame
      range_min: 0.0 #m
      range_max: 100.0 #m
      persistence: false
      timeout: 0.0 #0.0 seconds = all value's date are autorized

    lidar2_simu:
      topic: "lidar2_simu/scan"
      start_angle: 0.785398163 #45 deg in source frame
      end_angle: 5.497787144 #-45 = 315 deg in source frame
      scan_angle_offset: 0.0 #180 deg with rpLidars, but simulation doens't need shift as the start and end angles are well specified in the lidar frame
      range_min: 0.0 #m
      range_max: 100.0 #m
      persistence: false
      timeout: 0.0 #0.0 seconds = all value's date are autorized

    lidar1:
      topic: "lidar1/scan"
      start_angle: 0.785398163 #45 deg in source frame
      end_angle: 5.497787144 #-45 = 315 deg in source frame
      scan_angle_offset: 0.0 #180 deg with rpLidars, but angles are well specified
      range_min: 0.0 #m
      range_max: 100.0 #m
      persistence: false
      timeout: 0.0 #0.0 seconds = all value's date are autorized

    lidar2:
      topic: "lidar2/scan"
      start_angle: 0.785398163 #45 deg
      end_angle: 5.497787144 #-45 = 315 deg
      scan_angle_offset: 0.0 #180 deg with rpLidars, but angles are well specified
      range_min: 0.0 #m
      range_max: 100.0 #m
      persistence: false
      timeout: 0.0 #0.0 seconds = all value's date are autorized

    cam1:
      topic: "cam1/scan"
      start_angle: 0.0 #the values are already specified in scan msg
      end_angle: 6.283185307
      scan_angle_offset: 0.0
      range_min: 0.0 #m
      range_max: 100.0 #m
      persistence: true
      timeout: 0.0 #0.0 seconds = all value's date are autorized
      
    cam2:
      topic: "cam2/scan"
      start_angle: 0.0 #the values are already specified in scan msg
      end_angle: 6.283185307 
      scan_angle_offset: 0.0
      range_min: 0.0 #m
      range_max: 100.0 #m
      persistence: true
      timeout: 0.0 #0.0 seconds = all value's date are autorized