joystick_control_node:
  ros__parameters:
    #check gamepad inputs with another program to configure this file

    #keybiding for mobile base control
    linear_speed_axis: 0 #0 or 1
    angular_speed_axis: 1 #0 or 1
    max_linear_speed_up_button: 8
    max_linear_speed_down_button: 6
    max_angular_speed_up_button: 9
    max_angular_speed_down_button: 7
    front_camera_up_button: 2
    front_camera_down_button: 0
    back_camera_up_button: 3
    back_camera_down_button: 1
    assissted_teleoperation_mode_button: 4 #toggle assissted teleoperation mode
    emergency_button: 5 #toggle automatic security mode (prevent commands from other nodes by sending little ones) 
    arming_axis: 2 #The axis used to arm, disarm, configure and shutdown the mobile base, used as 4 buttons
    configure_state_direction: "left" #configure Triorb
    activate_state_direction: "up" #Activate Triorb
    deactivate_state_direction: "down" #Deactivate Triorb
    update_status_direction: "right" #button to connect to the Triorb or to update the status

    #mobile base config (we stay between 0.0 and 1.0 for call_m, this is a percentage, the call_m_supervisor package will then manage the good speed to send)
    max_linear_speed_axis_value_input: 32767.0 #check your gamepad on read mode to get it
    linear_speed_direction: -1 #-1 or 1
    max_angular_speed_axis_value_input: 32767.0
    angular_speed_direction: -1 #-1 or 1
    max_linear_speed_axis_value_wanted: 1.0 #the output twist message will contain speeds from 0.0 to this value
    max_angular_speed_axis_value_wanted: 1.0
    linear_speed_increment: 0.2 #(m/s))how much to change the maximum speed when changing it
    angular_speed_increment: 0.1 #(rad/s)
    camera_angle_increment: 18.0 #(degrees) how much to change the angle of the camera when changed (camera have position form 0 to 180deg, 0deg = looking completely down)

    #keybiding for arm control
    #(TO Do, add button to switch to Triorb control or Arm control, could use one of the pad button to switch)

    #output configurations
    rate: 50.0 #hz
    topic_main_cmd: "cmd_vel_teleop_joy" #topic to publish when in default mode
    topic_assissted_cmd: "cmd_vel_teleop_assist" #topic to publish when in assissted mode
